// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Session2.Context;

#nullable disable

namespace Session2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230622062817_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Session2.Models.Pizza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Pizzas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A traditional deep-dish pizza with sausage, cheese, and tomato sauce.",
                            Name = "Classic Chicago",
                            Price = 100.0,
                            Size = 0
                        },
                        new
                        {
                            Id = 2,
                            Description = "A deep-dish pizza loaded with assorted vegetables and cheese",
                            Name = "Chicago Veggie",
                            Price = 200.0,
                            Size = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "A deep-dish pizza packed with spicy meats, cheese, and tomato sauce",
                            Name = "Spicy Meat Lover's",
                            Price = 300.0,
                            Size = 2
                        },
                        new
                        {
                            Id = 4,
                            Description = "A classic brick oven pizza with fresh mozzarella, basil, and tomatoes",
                            Name = "Margherita",
                            Price = 200.0,
                            Size = 1
                        },
                        new
                        {
                            Id = 5,
                            Description = "A flavorful brick oven pizza topped with olives, feta cheese, and vegetables",
                            Name = "Mediterranean Delight",
                            Price = 300.0,
                            Size = 2
                        },
                        new
                        {
                            Id = 6,
                            Description = " An authentic Italian pizza with fresh mozzarella, basil, and tomatoes.",
                            Name = "Margherita Classica",
                            Price = 300.0,
                            Size = 2
                        },
                        new
                        {
                            Id = 7,
                            Description = " A heavenly Italian pizza topped with a blend of four cheeses.",
                            Name = "Quattro Formaggi",
                            Price = 200.0,
                            Size = 1
                        },
                        new
                        {
                            Id = 8,
                            Description = " A scrumptious Neapolitan pizza topped with artichokes, ham, mushrooms, and olives",
                            Name = "Margherita Napoletana",
                            Price = 300.0,
                            Size = 2
                        },
                        new
                        {
                            Id = 9,
                            Description = " A delightful Neapolitan pizza featuring sausage and sautéed broccoli rabe.",
                            Name = "Salsiccia e Friarielli",
                            Price = 300.0,
                            Size = 2
                        },
                        new
                        {
                            Id = 10,
                            Description = " A vibrant California-style pizza loaded with fresh vegetables and goat cheese.",
                            Name = "California Veggie",
                            Price = 200.0,
                            Size = 1
                        },
                        new
                        {
                            Id = 11,
                            Description = " A unique California-style pizza with a peanut sauce base, chicken, and veggies.",
                            Name = "BBQ Chicken",
                            Price = 300.0,
                            Size = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
